# Create users, check if username exists, show if username exists.

- name: Creating user, checking
  hosts: all
  vars:
    - user: joyfuldamnation
  tasks:
    - name: Check if file already exists
      command: ls /Documents/{{ user }}/myfile
      register: file_exists
      ignore_errors: yes

    - name: create file for user
      file:
        path: /home/{{ user }}/myfile
        state: touch
      when: file_exists is failed

    - name: show message if file exists
      debug:
        msg: This user file already exists.
      when: file_exists is succeeded