- name: Mongodb installation, Usage and Removal
  hosts: localhost
  become: yes
  tasks:
    - name: MongoDB - Import public key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
      when: ansible_os_family =="Debian"

    - name: MongoDB - Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-3.2.list'
        repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
        state: present
        update_cache: yes
      when: ansible_os_family =="Debian"

    - name: MongoDB | Install the packages in Debian
      apt: 
        name: "{{ item }}" 
        state: present 
        update_cache: yes
      with_items:
        - mongodb-org
        - mongodb-org-server
        - mongodb-org-shell
        - mongodb-org-mongos
        - mongodb-org-tools
      notify:
        - restart mongodb
      when: ansible_os_family =="Debian" 
  
    - name: Installing in RedHat
      yum:
        name: "{{item}}"
      with_items:
        - mongodb-org
      when: ansible_os_family =="RedHat" 

    - name: Ensuring Mongodb service is running
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Uninstalling Mongodb
      apt:
        name: "{{item}}"
        state: absent
      become: true
      with_items:
        - mongodb-org