#Just running a Mysql Docker container
- name: Running a MySQL Docker container
  hosts: localhost
  vars:
    db_volume: db_data
    docker_network: ansible_net
    image: "{{ lookup('env', 'image') }}"
    MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    ports: "{{ lookup('env', 'ports') }}"
  tasks:
    - name: Launch mysql database container
      community.docker.docker_container:
        name: db
        image: lookup('env', 'image')
        volumes:
          - "{{db_volume}}:/var/lib/mysql"
        restart: true
        env:
          MYSQL_ROOT_PASSWORD: lookup('env', 'MYSQL_ROOT_PASSWORD')
          MYSQL_DATABASE: database
          MYSQL_USER: pmm
          MYSQL_PASSWORD: password
        ports: lookup('env', 'ports')
        command: docker wait db
    - name: running commands
      community.docker.docker_container:
        name: db
        state: present
        image: lookup('env', 'image')
        command:
          - CREATE USER 'pmm'@'localhost' IDENTIFIED BY 'pass' WITH MAX_USER_CONNECTIONS 10;
          - GRANT SELECT, PROCESS, REPLICATION CLIENT, RELOAD ON . TO 'pmm'@'localhost';
          - SET GLOBAL slow_query_log='ON';
          - SET GLOBAL long_query_time=0;
          - SET GLOBAL log_slow_rate_limit=1;
