- name: PostgreSQL installation, Usage and Removal
  hosts: localhost
  vars: 
    PostgreSQL_VERSION: "{{ lookup('env', 'PostgreSQL_VERSION') }}"
  tasks:
    - name: Install version with python support
      apt:
        name: "{{item}}"
      with_items:
        - postgresql
        - python3-psycopg2
      when: lookup('env', 'PostgreSQL_VERSION') == "pythonenabled" 
  
    - name: Install version standard version 13
      apt:
        name: "{{item}}"
      with_items:
        - postgresql
      when: lookup('env', 'PostgreSQL_VERSION') == "pythondisabled" 

    - name: Ensuring PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes
    
    - name: Uninstalling PostgreSQL
      apt:
        name: "{{item}}"
        state: absent
      become: true
      with_items:
        - postgresql