- name: MySQL installation, Usage and Removal
  hosts: localhost
  vars: 
    MYSQL_VERSION: "{{ lookup('env', 'MYSQL_VERSION') }}"
  tasks:
    - name: Install version 5.7
      package:
        name: mysql-server-core-5.7
      with_items:
        - mysql-client-core-5.7
      when: lookup('env', 'MYSQL_VERSION') == "5.7" 
  
    - name: Install version 8.0
      package:
        name: mysql-server
      with_items:
        - mysql-client
      when: lookup('env', 'MYSQL_VERSION') == "8.0" 

    - name: Ensuring MySQL service is running
      service:
        name: mysql-server
        state: started
    
    - name: Uninstalling MySQL
      package:
        name: mysql-server
        state: absent
      become: true