- name: MySQL installation, Usage and Removal
  hosts: localhost
  vars: 
    MYSQL_VERSION: "{{lookup('switch_hosts.yml', '/etc/ansible/localhost_vars')}}"
  tasks:
    - name: Install version 5.7
      package:
        name: mysql-server-core-5.7
      with_items:
        - mysql-client-core-5.7
      when: MYSQL_VERSION == 5.7
  
    - name: Install version 8.0
      package:
        name: mysql-server
      with_items:
        - mysql-client
      when: MYSQL_VERSION == 8.0

    - name: Ensuring MySQL service is running
      service:
        name: MySQL
        state: started
    
    - name: Uninstalling MySQL
      package:
        name: MySQL
        state: absent
      become: true