- name: MySQL installation, Usage and Removal
  hosts: localhost
  become: yes
  vars: 
    MYSQL_VERSION: "{{ lookup('env', 'MYSQL_VERSION') }}"
  tasks:
    - name: Install version 5.7
      apt:
        name: "{{item}}"
      with_items:
        - mysql-community-server
        - mysql-client
        - python3-mysqldb-dbg
        - python3-pymysql
      when: lookup('env', 'MYSQL_VERSION') == "5.7" 
  
    - name: Install version 8.0
      apt:
        name: "{{item}}"
      with_items:
        - mysql-server
        - mysql-client
        - python3-mysqldb-dbg
        - python3-pymysql

      when: lookup('env', 'MYSQL_VERSION') == "8.0" 

    - name: Ensuring MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Uninstalling MySQL
      apt:
        name: "{{item}}"
        state: absent
      become: true
      with_items:
        - mysql-server
        - mysql-client
        - python3-mysqldb-dbg
        - python3-pymysql